version: '3'

services:
  backend:
    image: pmontgomery27/python-backend-docker
    ports:
      - "3000:3000"
  frontend:
    container_name: docker-react-c
    image: pmontgomery27/docker-react-i
    ports:
      - "8080:80"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - /app/node_modules
      - .:/app
  cpp-server:
    image: pmontgomery27/cpp-server
    ports:
      - "2000:2000"
  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
