version: '3'

http:
  middlewares:
    cors-headers:
      headers:
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "OPTIONS"
        accessControlAllowOrigin: "*"
        accessControlMaxAge: 86400
        accessControlAllowHeaders:
          - "Content-Type"

services:
  traefik:
      image: traefik:v2.4
      command:
        - "--log.level=DEBUG"
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.web.address=:80"
        - "--entrypoints.websecure.address=:443"
        - "--entrypoints.webinternal.address=:3000"
        - "--entrypoints.webcpp.address=:2000"
        - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
        - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
        - "--certificatesresolvers.myresolver.acme.email=up916639@email.com"
        - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      ports:
        - "80:80"
        - "443:443"
        - "8080:8080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./letsencrypt:/letsencrypt
      networks:
        - webnet
  backend:
    image: pmontgomery27/python-backend-docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.airlinestock.co.uk`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.middlewares=redirect-to-https"
      - "traefik.http.routers.backend-secured.rule=Host(`api.airlinestock.co.uk`)"
      - "traefik.http.routers.backend-secured.entrypoints=websecure"
      - "traefik.http.routers.backend-secured.tls.certresolver=myresolver"
    networks:
      - webnet
  frontend:
    container_name: docker-react-c
    image: pmontgomery27/docker-react-i
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`airlinestock.co.uk`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.frontend-secured.rule=Host(`airlinestock.co.uk`)"
      - "traefik.http.routers.frontend-secured.entrypoints=websecure"
      - "traefik.http.routers.frontend-secured.tls.certresolver=myresolver"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - /app/node_modules
      - .:/app
    networks:
      - webnet
  cpp-server:
    image: pmontgomery27/cpp-server
    ports:
      - "2000:2000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cpp-server.rule=Host(`cpp.airlinestock.co.uk`)"
      - "traefik.http.routers.cpp-server.entrypoints=webcpp"
      - "traefik.http.routers.cpp-server.middlewares=redirect-to-https"
      - "traefik.http.routers.cpp-server-secured.rule=Host(`cpp.airlinestock.co.uk`)"
      - "traefik.http.routers.cpp-server-secured.entrypoints=websecure"
      - "traefik.http.routers.cpp-server-secured.tls.certresolver=myresolver"
    networks:
      - webnet

networks:
  webnet: