version: '3'

services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
  frontend:
    container_name: docker-react-c
    image: docker-react-i
    build:
      context: .
    ports:
      - "8080:80"
    environment:
      CHOKIDAR_USEPOLLING: "true"
