# Use an official Python runtime as a parent image
FROM python:3.11.2-slim-buster

# Set the working directory to /app
WORKDIR /app

# Copy the rest of the application code to the working directory
COPY . .

# Install dependencies
RUN pip install -r requirements.txt

# Install gunicorn
RUN pip install gunicorn

# Expose the port your application runs on
EXPOSE 3000

# Start the backend server
CMD ["gunicorn", "run:app", "-b", "0.0.0.0:3000", "--workers=4"]