# Testing stage
FROM python:3.11.2-slim-buster as tester
WORKDIR /app
# Copy just what you need to install dependencies, then the rest of the app.
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
# No CMD here since we'll override it when we run the container for tests

# Production stage
FROM python:3.11.2-slim-buster AS production-ready
WORKDIR /app

# Set the working directory to /app
WORKDIR /app

# Copy the rest of the application code to the working directory
COPY . .

# Install dependencies
RUN pip install -r requirements.txt

# Install gunicorn
RUN pip install gunicorn

# Expose the port your application runs on
EXPOSE 3000

# Start the backend server
CMD ["gunicorn", "run:app", "-b", "0.0.0.0:3000", "--workers=4"]
