# Testing stage
FROM python:3.11.2-slim-buster as tester
WORKDIR /app
COPY . .
RUN pip install -r requirements.txt
# No CMD here since we'll override it when we run the container for tests

# Production stage
FROM python:3.11.2-slim-buster
WORKDIR /app

# Copy the application code from the tester stage
COPY --from=tester /app /app

# Install gunicorn for production (you could also consider moving this to requirements.txt)
RUN pip install gunicorn

# Expose the port your application runs on
EXPOSE 3000

# Start the backend server
CMD ["gunicorn", "run:app", "-b", "0.0.0.0:3000", "--workers=4"]
